name: Build Godot Workshop Utility

on:
  push:
    tags:
      - '*'
env:
  GODOT_VERSION: 4.6.3
  EXPORT_NAME: GodotWorkshopUtility
  PROJECT_PATH: godot-workshop-utility

jobs:
  export:
    name: Export Godot Workshop Utility
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p build/windows
          mkdir -v -p build/linux
          mkdir -v -p build/mac
          cp templates/steam_api64.dll build/windows/
          cp templates/libsteam_api.so build/linux/
      - name: Build
        run: |
          GODOT_BIN="$(readlink -f templates/godotsteam.463.editor.x86_64)"
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          $GODOT_BIN --headless --verbose --export-release "windows" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
          $GODOT_BIN --headless --verbose --export-release "linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
          $GODOT_BIN --headless --verbose --export-release "macos" "$EXPORT_DIR/mac/$EXPORT_NAME.zip"
      - name: Extract Mac version
        run: |
          unzip -d build/mac/ build/mac/$EXPORT_NAME.zip
          rm build/mac/$EXPORT_NAME.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: build/windows
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: linux
          path: build/linux
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: mac
          path: build/mac
